cc_binary(
    name = "blink",
    srcs = ["blink.cpp"],
    deps = [
        "@pico-sdk//src/rp2_common/pico_stdlib:pico_stdlib",
        "@pico-sdk//src/rp2_common/pico_stdio_usb:pico_stdio_usb",
	      "@fmt//:fmt",
    ],
)

